### ISSUE TITLE
no contribution possible?

### ISSUE THREAD

**Issue by fiws** [TestArmada/testarmada.github.io#3]
Hi,

i actually wanted to create a PR for this repo, but then I noticed that there are scss source maps to files non-existent in this repo (in `/styles`). 

Is this repo just a build result or am I overlooking something?

**Comment by geekdave** [comment]
@fiws Good catch :)  This site is actually based on the marionettejs site (MIT Licensed) and was hastily slapped together.  The marionetteJS site has a whole build system, and in the interest of time, I just checked in the generated files here.

I've logged an issue to put the build system in place here: https://github.com/TestArmada/testarmada.github.io/issues/4

In the meantime, if you find anything in need of repair, please let me know and I can fix it manually.  Sorry for the dust around here (or missing floorboards)!

**Comment by fiws** [comment]
ok
This is my PR:

## `_header.scss:89`

`.global-nav`

```
 + transform: translateZ(0);
```

## `_back_to_top_button.scss:8`

`.top`

```
 + transform: translateZ(0);
```

Don't know if the source maps are actually correct of course.

## Effect

Better scroll performance. Scrolling can be GPU accelerated.

### [Video (before/after)](https://photos.google.com/share/AF1QipO8J72VyVBhxe5b73GjLB273WwCCFVLyHytNiiMC22c1pIMMmWwHwOYaPfkfK-FQA/photo/AF1QipNC8pVZISn2rhJlx-NLAq7QPY8leRSIEdc0D8OA?key=eUxldzlMbXd2SUY0X2xERUMtQ254WmtsN1FlVmhB)
